# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7881204e83faed70242dc6641bbd1aa787d1d872bc23fb77bd69a9ab1b9efd472ee856e276ac24bbbeea823d2b17d92afdcdd01e6858f2f89074d1c2f6d3b726

test:
  secret_key_base: be962ac87d4f842ec963f376ed571c27166cb5c52bb6a58b3f043c9dd3cdbb6a04e4a7b59d1670e1ede9d4203b671243bd099b4228e59c3229db9d659fa0e062

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
